name: Release on Tag

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: actions/setup-go@v6.4.0
        with:
          architecture: x64

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build 
        run: |
          make build-windows SERVER_URL=https://artikulo.cz/install PUBLIC_KEY_HEX=b504b2a00184a0190ecec1ad92aedb077ea3dd8a79da417a767d62d48e8c89a3

      - name: Prepare GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: true
          prerelease: false
          files: server/get_artikulo.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
